### PR TITLE
Adds Signal.send_async for asyncio

### PR DESCRIPTION
**Pull request by jek**
Adds Signal.send_async for asyncio, ala #17 and AsyncBlink.

### CODE REVIEW

**Comment by yackx** [comment]
This PR was practically ready IMO. What we did:

- Merge `master` into `feature/send-async` to refresh the branch (we needed to enable support of more recent versions of Python and drop support of older versions) https://github.com/jek/blinker/pull/18/commits/74df4c141934c01b3b2f7e27f8438b07b1c12b63
- Fix an incorrect import statement (`create_task` and `ensure_future`) https://github.com/jek/blinker/pull/18/commits/5936e96bb059dc766d0e87fc569f61dfb5eca963
- Add some documentation (`README` and `rst`) https://github.com/jek/blinker/pull/18/commits/c7b83a18a54efa9e08a9446e2d16956ee5fe353b

Waiting for feedback...

Co-author: @no-lab

**Review by yackx — APPROVED** [review]

**Comment by yackx** [comment]
closes #17

**Comment by davidism** [comment]
I'm going to revert this so that it is not in the next release. I know it was reviewed recently, but it was originally written in 2015 when async was very different. Now that this is part of Pallets-Eco and is used by both sync Flask and async Quart, we'll review how we want to go about supporting async. Quart has a different set of patches it uses to enable async in existing blinker, so @pgjones will review this more.

**Comment by davidism** [comment]
I've rebased the [`feature/send-async`](https://github.com/pallets-eco/blinker/commits/feature/send-async) branch to be ready to re-apply those changes if we decide to go with them.

**Pull request merged**
